/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LedgerEntryType = "ADJUSTMENT" | "CAPTURE" | "RECHARGE" | "RELEASE" | "RESERVE";

export type OutboxStatus = "FAILED" | "PENDING" | "PUBLISHED";

export type PointOperation = "ACTION" | "RECHARGE";

export type PointTransactionStatus = "CAPTURED" | "FAILED" | "RECHARGED" | "RELEASED" | "RESERVED";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface OutboxEvents {
  aggregate_id: string;
  aggregate_type: string;
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  payload: Json;
  published_at: Timestamp | null;
  status: Generated<OutboxStatus>;
}

export interface PointLedgerEntries {
  available_delta: Generated<number>;
  created_at: Generated<Timestamp>;
  entry_type: LedgerEntryType;
  held_delta: Generated<number>;
  id: Generated<string>;
  transaction_id: string;
  wallet_id: string;
}

export interface PointTransactions {
  amount: number;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string;
  idempotency_scope: string;
  operation: PointOperation;
  parent_transaction_id: string | null;
  request_hash: string;
  response_payload: Json | null;
  status: PointTransactionStatus;
  updated_at: Generated<Timestamp>;
  wallet_id: string;
}

export interface Wallets {
  available_points: Generated<number>;
  created_at: Generated<Timestamp>;
  held_points: Generated<number>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  version: Generated<number>;
}

export interface DB {
  outbox_events: OutboxEvents;
  point_ledger_entries: PointLedgerEntries;
  point_transactions: PointTransactions;
  wallets: Wallets;
}
